[general]

[window]
dynamic_padding = true
opacity = 0.85

[font]
normal.family = "NotoSansM Nerd Font"
# normal.family = "Google Sans Code"
size = 12
# offset = { x = 0, y = 0 }
# builtin_box_drawing = false

