# Execute your favorite apps at launch
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprpaper
exec-once = hypridle
exec-once = hyprsunset
exec-once = snackdaemon daemon
# exec-once = hyprpm reload -n
# exec-once = nm-applet
exec-once = fcitx5
exec-once = eww daemon
# exec-once = eww open statusbar
exec-once = nix develop ~/Desktop/Development/eucalyptus-twig -c ~/Desktop/Development/eucalyptus-twig/target/release/eucalyptus-twig
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data

# Some default env vars.
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt6ct # change to qt6ct if you have that

env = ELECTRON_OZONE_PLATFORM_HINT, auto
env = GDK_BACKEND,wayland,x11
env = QT_QPA_PLATFORM,wayland;xcb
# env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORM,wayland;xcb
# Variables for nvidia, see https://wiki.hyprland.org/Nvidia/
# env = LIBVA_DRIVER_NAME,nvidia
# env = XDG_SESSION_TYPE,wayland
# env = GBM_BACKEND,nvidia-drm
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia
# env = WLR_NO_HARDWARE_CURSORS,1

# env for driver
env = LIBVA_DRIVER_NAME, radeonsi
env = VDPAU_DRIVER, radeonsi
