# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# windowrule {
#     name = suppress-maximize
#     match:class = .*
#     suppress_event = fullscreen maximize fullscreenoutput
# }

windowrule {
    name = firefox-pip-float
    match:class = firefox
    match:title = 子母畫面
    float = true
}

# FreeCad on Wayland now has a issue where you can see the wallpaper through it: <https://github.com/FreeCAD/FreeCAD/issues/6177>
windowrule {
    name = FreeCAD-opaque
    match:class = org\.freecad\.FreeCAD
    opaque = true
    force_rgbx = true
}

layerrule {
    name = ewwStatusBar
    match:namespace = ewwStatusBar
    blur = true
    ignore_alpha = 0
}
layerrule {
    name = ewwSnackBar
    match:namespace = ewwSnackBar
    blur = true
    ignore_alpha = 0
    animation = slide
}
layerrule {
    name = ewwPowerMenu
    match:namespace = ewwPowerMenu
    blur = true
    # ignore_alpha = 0
    dim_around = true
    animation = slide
}
layerrule {
    name = rofi
    match:namespace = rofi
    blur = true
    ignore_alpha = 0
    dim_around = true
    animation = slide
}
layerrule {
    name = eucalyptus-twig-power-menu
    match:namespace = eucalyptus-twig-power-menu
    blur = true
    # ignore_alpha = 0
    dim_around = true
    animation = slide
}
