splash = false

# wallpaper {
#     monitor =
#     path = ~/.config/hypr/wallpapers/wall2.png
# }
# wallpaper {
#     monitor =
#     path = ~/.config/hypr/wallpapers/rim-wallpaper.jpg
# }
# wallpaper {
#     monitor =
#     path = ~/.config/hypr/wallpapers/rim-wallpaper2.jpg
# }
# wallpaper {
#     monitor =
#     path = ~/.config/hypr/wallpapers/rim-wallpaper2-2.png
# }
# wallpaper {
#     monitor =
#     path = ~/.config/hypr/wallpapers/tank-cat-blue.jpg
# }
wallpaper {
    monitor =
    path = ~/.config/hypr/wallpapers/koana-1.png
}
